run tests

diff --git a/django_gunicorn_pgsql/docker-entrypoint b/django_gunicorn_pgsql/docker-entrypoint
--- a/django_gunicorn_pgsql/docker-entrypoint
+++ b/django_gunicorn_pgsql/docker-entrypoint
@@ -16,14 +16,14 @@ find ./ -iname "*.pyc" -delete
 ./manage.py migrate
 
 # Django Test
-#./manage.py test -v 2 --noinput
-#status=$?
+./manage.py test -v 2 --noinput
+status=$?
 
-#if [ "$status" -ne 0 ] ; 
-#then
-#   echo -e "Tests Failed"
-#   exit 1
-#fi
+if [ "$status" -ne 0 ] ; 
+then
+   echo -e "Tests Failed"
+   exit 1
+fi
 
 if [[ $1 == "server" ]]; then
    exec gunicorn -b [::]:8000 -k 'gevent' --timeout 120 -w ${WORKERS} ${APPNAME}.wsgi
